import type { EquipmentDef, FacilityId } from './types';

export const EQUIPMENT: EquipmentDef[] = [
  {
    id: 'P-401',
    facilityId: 'northfield-wrrf',
    nodeId: 'influent',
    label: 'Inlet Screw Pump 1',
    kind: 'pump',
    mode: 'AUTO',
    running: true,
    setpoint: 68,
    setpointUnit: '%',
    setpointMin: 0,
    setpointMax: 100,
  },
  {
    id: 'P-402',
    facilityId: 'northfield-wrrf',
    nodeId: 'influent',
    label: 'Inlet Screw Pump 2',
    kind: 'pump',
    mode: 'AUTO',
    running: true,
    setpoint: 64,
    setpointUnit: '%',
    setpointMin: 0,
    setpointMax: 100,
  },
  {
    id: 'P-403',
    facilityId: 'northfield-wrrf',
    nodeId: 'influent',
    label: 'Auxiliary Storm Pump',
    kind: 'pump',
    mode: 'AUTO',
    running: false,
    setpoint: 0,
    setpointUnit: '%',
    setpointMin: 0,
    setpointMax: 100,
  },
  {
    id: 'SC-201',
    facilityId: 'northfield-wrrf',
    nodeId: 'primary',
    label: 'Primary Scraper Bridge',
    kind: 'scraper',
    mode: 'AUTO',
    running: true,
    setpoint: 0.032,
    setpointUnit: 'rpm',
    setpointMin: 0,
    setpointMax: 0.08,
  },
  {
    id: 'BL-301',
    facilityId: 'northfield-wrrf',
    nodeId: 'bioreactor',
    label: 'Aeration Blower A',
    kind: 'blower',
    mode: 'AUTO',
    running: true,
    setpoint: 72,
    setpointUnit: '%',
    setpointMin: 0,
    setpointMax: 100,
  },
  {
    id: 'BL-302',
    facilityId: 'northfield-wrrf',
    nodeId: 'bioreactor',
    label: 'Aeration Blower B',
    kind: 'blower',
    mode: 'AUTO',
    running: true,
    setpoint: 68,
    setpointUnit: '%',
    setpointMin: 0,
    setpointMax: 100,
  },
  {
    id: 'SC-202',
    facilityId: 'northfield-wrrf',
    nodeId: 'secondary',
    label: 'Secondary Scraper Bridge',
    kind: 'scraper',
    mode: 'AUTO',
    running: true,
    setpoint: 0.028,
    setpointUnit: 'rpm',
    setpointMin: 0,
    setpointMax: 0.08,
  },
  {
    id: 'P-501',
    facilityId: 'northfield-wrrf',
    nodeId: 'secondary',
    label: 'RAS Pump Station',
    kind: 'pump',
    mode: 'AUTO',
    running: true,
    setpoint: 62,
    setpointUnit: '%',
    setpointMin: 0,
    setpointMax: 100,
  },
  {
    id: 'DS-601',
    facilityId: 'northfield-wrrf',
    nodeId: 'nutrient',
    label: 'Coagulant Dosing Skid',
    kind: 'dosing',
    mode: 'AUTO',
    running: true,
    setpoint: 18.2,
    setpointUnit: 'L/h',
    setpointMin: 0,
    setpointMax: 60,
  },
  {
    id: 'UV-701',
    facilityId: 'northfield-wrrf',
    nodeId: 'uv',
    label: 'UV Bank 1',
    kind: 'uv',
    mode: 'AUTO',
    running: true,
    setpoint: 80,
    setpointUnit: '%',
    setpointMin: 0,
    setpointMax: 100,
  },
  {
    id: 'UV-702',
    facilityId: 'northfield-wrrf',
    nodeId: 'uv',
    label: 'UV Bank 2',
    kind: 'uv',
    mode: 'MANUAL',
    running: false,
    setpoint: 0,
    setpointUnit: '%',
    setpointMin: 0,
    setpointMax: 100,
  },
  {
    id: 'CF-801',
    facilityId: 'northfield-wrrf',
    nodeId: 'dewatering',
    label: 'Dewatering Centrifuge',
    kind: 'centrifuge',
    mode: 'AUTO',
    running: true,
    setpoint: 2850,
    setpointUnit: 'rpm',
    setpointMin: 0,
    setpointMax: 4000,
  },
  {
    id: 'GV-901',
    facilityId: 'northfield-wrrf',
    nodeId: 'gasholder',
    label: 'Biogas Flare Valve',
    kind: 'valve',
    mode: 'AUTO',
    running: false,
    setpoint: 0,
    setpointUnit: '%',
    setpointMin: 0,
    setpointMax: 100,
  },

  {
    id: 'EB-P-101',
    facilityId: 'eastbank-industrial',
    nodeId: 'influent',
    label: 'Equalisation Pump',
    kind: 'pump',
    mode: 'AUTO',
    running: true,
    setpoint: 58,
    setpointUnit: '%',
    setpointMin: 0,
    setpointMax: 100,
  },
  {
    id: 'EB-DS-102',
    facilityId: 'eastbank-industrial',
    nodeId: 'preliminary',
    label: 'Caustic Dosing Skid',
    kind: 'dosing',
    mode: 'AUTO',
    running: true,
    setpoint: 62.4,
    setpointUnit: 'L/h',
    setpointMin: 0,
    setpointMax: 200,
  },
];

const EXTRA: EquipmentDef[] = [];

export function registerEquipment(defs: EquipmentDef[]) {
  for (const def of defs) {
    if (!EXTRA.some((e) => e.id === def.id) && !EQUIPMENT.some((e) => e.id === def.id)) {
      EXTRA.push(def);
    }
  }
}

export function equipmentForFacility(facilityId: FacilityId): EquipmentDef[] {
  return [...EQUIPMENT, ...EXTRA].filter((e) => e.facilityId === facilityId);
}

export function equipmentForNode(facilityId: FacilityId, nodeId: string): EquipmentDef[] {
  return [...EQUIPMENT, ...EXTRA].filter((e) => e.facilityId === facilityId && e.nodeId === nodeId);
}

export function cloneEquipment(templateFacilityId: FacilityId, newFacilityId: FacilityId): EquipmentDef[] {
  return EQUIPMENT.filter((e) => e.facilityId === templateFacilityId).map((e) => ({
    ...e,
    id: `${newFacilityId}__${e.id}`,
    facilityId: newFacilityId,
  }));
}
